"use client";

import { CSSProperties, FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { addDoc, collection, doc, onSnapshot, orderBy, query, where } from "firebase/firestore";
import { onAuthStateChanged, User } from "firebase/auth";
import { ArrowLeft, CalendarDays, Check, CircleUserRound, Clock3, MapPin, Users } from "lucide-react";
import { auth, db, firebaseConfigured } from "@/lib/firebase";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { authErrorMessage, loginWithEmail, loginWithGoogle } from "@/lib/auth";
import { PublicHeader } from "@/app/components/public-header";

type FormField={id:string;label:string;type:"text"|"email"|"tel"|"textarea"|"select"|"radio"|"checkbox";required:boolean;options?:string[]};
type EventItem={id:string;title:string;date:string;place:string;summary:string;capacity:number;status:"open"|"closed";formSchema:FormField[]};
type Reservation={id:string;eventTitle:string;createdAt:string;status:string};
const LOGO="https://upload.wikimedia.org/wikipedia/commons/1/17/K-ON_anime_wordmark.svg";
const statusLabel:Record<string,string>={received:"접수",reviewing:"검토 중",confirmed:"확정",completed:"안내 완료"};

export default function EventsClient(){
  const [events,setEvents]=useState<EventItem[]>([]),[selected,setSelected]=useState<EventItem|null>(null),[user,setUser]=useState<User|null>(null),[reservations,setReservations]=useState<Reservation[]>([]),[siteName,setSiteName]=useState("K-ON! FANDOM KR"),[logo,setLogo]=useState(LOGO),[toast,setToast]=useState("");
  useEffect(()=>{if(!firebaseConfigured||!auth||!db)return;const ua=onAuthStateChanged(auth,next=>setUser(next));const ue=onSnapshot(query(collection(db,"events"),orderBy("date","asc")),snap=>setEvents(snap.docs.map(item=>({id:item.id,...item.data()} as EventItem))));const us=onSnapshot(doc(db,"siteSettings","main"),snap=>{if(!snap.exists())return;const data=snap.data();setSiteName(String(data.siteName||"K-ON! FANDOM KR"));setLogo(String(data.logoUrl||LOGO));});return()=>{ua();ue();us();};},[]);
  useEffect(()=>{if(!db||!user)return;return onSnapshot(query(collection(db,"reservations"),where("userId","==",user.uid)),snap=>setReservations(snap.docs.map(item=>({id:item.id,...item.data()} as Reservation)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));},[user]);
  async function eventLogin(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!auth)return;const data=new FormData(e.currentTarget);try{await loginWithEmail(auth,String(data.get("email")),String(data.get("password")));setToast("로그인했습니다.");}catch(error){setToast(authErrorMessage(error));}}
  async function eventGoogleLogin(){if(!auth)return;try{await loginWithGoogle(auth);setToast("Google 계정으로 로그인했습니다.");}catch(error){setToast(authErrorMessage(error));}}
  async function reserve(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;if(!user){setToast("예약하려면 먼저 로그인해 주세요.");return}if(!db)return;const form=new FormData(e.currentTarget);const answers=Object.fromEntries(selected.formSchema.map(field=>[field.id,String(form.get(field.id)||"")]));await addDoc(collection(db,"reservations"),{userId:user.uid,userEmail:user.email,eventId:selected.id,eventTitle:selected.title,answers,createdAt:new Date().toISOString(),status:"received"});setSelected(null);setToast("예약이 접수되었습니다. 내 예약에서 상태를 확인하세요.");}
  function field(question:FormField){if(question.type==="textarea")return <Textarea name={question.id} required={question.required}/>;if(question.type==="select")return <select name={question.id} required={question.required}><option value="">선택해 주세요</option>{question.options?.map(option=><option key={option}>{option}</option>)}</select>;return <Input name={question.id} type={question.type} required={question.required}/>;}
  return <main className="events-page" style={{"--accent":"#e85f7d"} as CSSProperties}><PublicHeader siteName={siteName} logoUrl={logo} active="events" actions={user?<Link className="member-state" href="/mypage"><CircleUserRound/>{user.email}</Link>:<span className="member-state"><CircleUserRound/>로그인 필요</span>}/>
    <section className="events-hero"><div><Link href="/"><ArrowLeft/>홈으로 돌아가기</Link><p>AFTER SCHOOL EVENT</p><h1>행사·예약</h1><span>좋아하는 음악과 사람을 만나는 시간을 신청하세요.</span></div></section>
    <div className="events-content"><div className="events-heading"><div><small>TEA TIME CALENDAR</small><h2>다가오는 팬 행사</h2></div><p>행사를 선택하면 관리자가 만든 신청폼을 이 페이지에서 바로 작성할 수 있습니다.</p></div><div className="event-layout"><section className="event-list">{events.length?events.map((event,index)=><article className={`event-card ${selected?.id===event.id?"selected":""}`} key={event.id}><span>0{index+1}</span><p className="date"><CalendarDays/>{new Date(event.date).toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"short"})} · {new Date(event.date).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</p><h3>{event.title}</h3><p>{event.summary}</p><dl><div><dt><MapPin/>장소</dt><dd>{event.place}</dd></div><div><dt><Users/>정원</dt><dd>{event.capacity}명</dd></div></dl><Button disabled={event.status!=="open"} onClick={()=>setSelected(event)}>{event.status==="open"?"이 행사 신청하기":"신청 마감"}</Button></article>):<div className="event-empty">등록된 행사가 없습니다.</div>}</section><aside className="event-form-panel">{selected?<><div className="event-form-head"><small>APPLICATION FORM</small><h3>{selected.title}</h3><p><Clock3/>필수 항목을 입력해 주세요.</p></div>{user?<form className="form" onSubmit={reserve}>{selected.formSchema.map(question=><label className="event-question" key={question.id}>{question.label}{question.required&&<b>*</b>}{field(question)}</label>)}<Button><Check/>예약 신청 제출</Button></form>:<div className="event-login-gate"><CircleUserRound/><h3>로그인이 필요합니다</h3><p>행사 신청과 내 예약 상태 확인은 회원 전용입니다.</p><form className="form" onSubmit={eventLogin}><Input name="email" type="email" placeholder="이메일" required/><Input name="password" type="password" placeholder="비밀번호" required/><Button>로그인 후 신청</Button></form><Button type="button" variant="outline" onClick={eventGoogleLogin}>Google 계정으로 로그인</Button></div>}</>:<div className="event-form-empty"><CalendarDays/><h3>신청할 행사를 선택하세요</h3><p>왼쪽 행사 카드에서 신청 버튼을 누르면<br/>맞춤 신청폼이 열립니다.</p></div>}</aside></div>{user&&<section className="my-reservations"><div className="events-heading"><div><small>MY RESERVATIONS</small><h2>내 예약</h2></div></div>{reservations.length?<div className="reservation-list">{reservations.map(item=><div key={item.id}><span>{item.eventTitle}</span><time>{new Date(item.createdAt).toLocaleDateString("ko-KR")}</time><b>{statusLabel[item.status]||item.status}</b></div>)}</div>:<p className="empty-note">아직 신청한 행사가 없습니다.</p>}</section>}</div>{toast&&<button className="toast" onClick={()=>setToast("")}>{toast}</button>}</main>;
}
